#!/bin/sh
for i in `uci show system.ntp.server|cut -d= -f2|sed "s/'//g"`; do
  if ping -c1 $i >/dev/null; then
    server=1
    break
  fi
done
if [ "$server" ]; then
  clock no-led
else
  clock led
fi
