#!/bin/sh
if mkdir /tmp/time.lock 2>/dev/null; then
  pid=`pgrep time-write`
  if [ "$pid" ]; then
    brightness=`grep -o '[0-9]*' /proc/$pid/cmdline`
    kill $pid
    while pgrep time-write >/dev/null; do true; done
  fi
  seconds=S
  if [ $1 = seconds ] || [ $1 = no-seconds ] || [ $1 = blink ] || [ $1 = no-blink ]; then
    case $1 in
    seconds)
      rm -f /tmp/time.no-seconds
      ;;
    no-seconds)
      touch /tmp/time.no-seconds
      ;;
    blink)
      touch /tmp/time.blink
      ;;
    no-blink)
      rm -f /tmp/time.blink
      ;;
    esac
    [ -e /tmp/time.no-seconds ] && seconds=-
    [ -e /tmp/time.blink ] && blink=B
    [ "$brightness" ] || brightness=-
    time-write $brightness $seconds $blink &
  else
    [ -e /tmp/time.no-seconds ] && seconds=-
    [ -e /tmp/time.blink ] && blink=B
    case $1 in
    0)
      time-write - $seconds $blink &
      ;;
    1)
      time-write 0 $seconds $blink &
      ;;
    2)
      time-write 15 $seconds $blink &
      ;;
    esac
  fi
  rmdir /tmp/time.lock
fi
