#!/bin/sh
if mkdir /tmp/time.lock 2>/dev/null; then
  pid=`pgrep time-write`
  if [ "$pid" ]; then
    brightness=`grep -o '[0-9]*' /proc/$pid/cmdline`
    kill $pid
    while pgrep time-write >/dev/null; do true; done
  fi
  if [ $1 = led ] || [ $1 = no-led ]; then
    case $1 in
    led)
      touch /tmp/time.led
      ;;
    no-led)
      rm -f /tmp/time.led
      ;;
    esac
    [ -e /tmp/time.led ] && led=L
    [ "$brightness" ] || brightness=-
    time-write $brightness $led &
  else
    [ -e /tmp/time.led ] && led=L
    case $1 in
    0)
      time-write - $led &
      ;;
    1)
      time-write 0 $led &
      ;;
    2)
      time-write 15 $led &
      ;;
    esac
  fi
  rmdir /tmp/time.lock
fi
