#!/bin/sh
if mkdir /tmp/time.lock 2>/dev/null; then
  killall time-write 2>/dev/null
  while pgrep time-write >/dev/null; do true; done
  case $1 in
  off)
    time-write - &
    ;;
  night)
    time-write 0 &
    ;;
  day)
    time-write 15 &
    ;;
  esac
  rmdir /tmp/time.lock
fi
