#!/bin/sh
if mkdir /tmp/time.lock 2>/dev/null; then
  brightness=$(cat /proc/`pgrep time-write || echo ..`/cmdline 2>/dev/null | grep -o '[0-9]*')
  killall time-write 2>/dev/null
  while pgrep time-write >/dev/null; do true; done
  if [ $1 = seconds ] || [ $1 = no-seconds ]; then
    if [ $1 = no-seconds ]; then
      touch /tmp/time.no-seconds
    else
      rm -f /tmp/time.no-seconds
    fi
    if [ "$brightness" ]; then
      [ -e /tmp/time.no-seconds ] && PATH=/bin/no-seconds:$PATH
      time-write $brightness &
    fi
  else
    [ -e /tmp/time.no-seconds ] && PATH=/bin/no-seconds:$PATH
    case $1 in
    1)
      time-write 0 &
      ;;
    2)
      time-write 15 &
      ;;
    esac
  fi
  rmdir /tmp/time.lock
fi
